version: "3.9"
services:
  reqserver:
    build: .
    deploy:
      replicas: 3
    volumes:
      - mydb:/db
  nginx:
    image: nginx:latest
    ports:
      - "8083:8083"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mydb:
